### ISSUE TITLE
Add `PRIVATE_KEY` and `TEST_PRIVATE_KEY` repo secrets

### ISSUE THREAD

**Issue by MantisClone** [oceanprotocol/dbs_arweave#6]
# Problem

This repository is missing the `PRIVATE_KEY` and `TEST_PRIVATE_KEY` secrets. Without them, the automated tests fail.

# Solution

1. Create two Ethereum wallet accounts using Metamask.
2. Fund the first account with Goerli ETH and Mumbai MATIC. 
3. Add the first account's private key as a repo secret named `PRIVATE_KEY`.
4. Fund the second account with Goerli ETH, [Goerli WETH](https://goerli.etherscan.io/token/0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6), Mumbai MATIC, and [Mumbai WMATIC](https://mumbai.polygonscan.com/token/0x9c3C9283D3e44854697Cd22D3Faa240Cfb032889).
5. Add the second account's private key as a repo secret named `TEST_PRIVATE_KEY`.

![image](https://user-images.githubusercontent.com/2530913/215560542-c91bd44b-01a8-4b43-8a48-4efe7476d9c3.png)

# Details:

The automated tests run on the Goerli and Mumbai testnets.

* `PRIVATE_KEY` is the private key of the server's Ethereum wallet account
* `TEST_PRIVATE_KEY` is the private key of the client's Ethereum wallet account

The server needs an operational reserve of native gas fee tokens, enough to cover one full upload procedure (transferFrom, unwrap (withdraw), send, wrap (deposit), transfer).

The client needs enough gas fee tokens to call `approve` and enough wrapped tokens to cover the upload fee + reimburse the server's gas fees.

**Comment by MantisClone** [comment]
Response to TODO

> > @balessan @alexcos20 The tests fail because #6
> 
> @MantisClone ok, first step of #6 is:
> 
>  > Create two test accounts.
>  
>  Which test accounts are we talking about ? I mean, on which application ? I guess I have issue with my local version not running because of that too, would help understand the dependency on other solutions, if any :-)

When I said accounts, I meant Ethereum key pairs. The private key from each key pair is what needs to be stored as repository secrets. I don't have admin access to this repo so I cannot configure the repo secrets. I suspect that only @alexcos20 can do this.

I updated the task description to clarify this.

**Comment by balessan** [comment]
@MantisClone I tried to run the tests on my own fork, setting up the accounts before-hand, but it fails: https://github.com/balessan/dbs_arweave/actions/runs/4056830689/jobs/6981813295

Pretty sure it is an amount issue, I only have two wallets with:

- PRIVATE_KEY has 1 MATIC and 0.2 GoerliETH
- TEST_PRIVATE_KEY has 0.09933GoerliETH, 0.1WETH and 0.6695 MATIC. I cannot find a way to get WMATIC easily, any clue ?

**Comment by MantisClone** [comment]
@balessan You're correct. The tests fail because your `TEST_PRIVATE_KEY` account does not have enough WETH and WMATIC.

Call [deposit on the Mumbai WMATIC contract](https://mumbai.polygonscan.com/token/0x9c3c9283d3e44854697cd22d3faa240cfb032889?a=0x20c9560d42566d6ead1da3dc84137e84838fa696#writeContract#F5) to turn MATIC into WMATIC. The input parameter is the amount of MATIC you'd like to wrap.

Call [deposit on the Goerli WETH contract](https://goerli.etherscan.io/token/0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6#writeContract#F5) to turn ETH into WETH. The input parameter is the amount of ETH you'd like to wrap.

You can call these functions through the Mumbaiscan and Goerliscan websites.

**Comment by balessan** [comment]
Thanks @MantisClone, now locally it runs properly. I can go forward on the actual test of the integration :-) I will see with @alexcos20 to get the proper rights for the CI on this repository.

Because I have 500 HTTP status code errors on my backend but I think it is on my side.

**Comment by MantisClone** [comment]
@balessan Glad to hear it. 

Additional note for awareness: there's a large upload test that runs quarterly that requires 4 WMATIC.

 (copied from the README):

> Expensive, large upload test
>
> The large upload test is run periodically (quarterly) via Github Actions. It requires over 4 WMATIC in the client account (TEST_PRIVATE_KEY).
>
> Config: https://github.com/MantisClone/arweave-upload/blob/main/.github/workflows/ci_expensive.yml

**Comment by balessan** [comment]
This one is still valid though. I will check with @alexcos20 .

**Comment by jamiehewitt15** [comment]
I'm not sure this testing approach is going to work for us. The CI will run on every commit which means we're quickly going to run out of Georli Eth on the test account. It's going to be a pain keeping it topped up. 

It would be better to mock the responses from bundlr, rather than creating actual transactions and doing a live upload each time. This would make the tests a lot more reliable and save us from having to top up accounts with ETH & MATIC

**Comment by jamiehewitt15** [comment]
I've added private keys for the tests
