### ISSUE TITLE
Signature mismatch between the DBS and DBS_Arweave

### ISSUE THREAD

**Issue by balessan** [oceanprotocol/dbs_arweave#9]
**Describe the bug**

Ping @MantisClone for insights.

When trying to update files, the signature computation from the DBS itself and from this project do not match.

The error I am currently getting looks like:

```sh
upload request: {"quoteId":"9ee450d4653519a44a178e77a050d1cd","nonce":"1768214571","signature":"8d230a13ceb3c6f4ff6c2ad86af1c0b3958fc1fe98a2b260ce828fc204ec32b6","files":["ipfs://Qmds3hSuS8vifPPiCYZ5zXwy2wBrx6JxkAbkTs7oAx8U6f","ipfs://Qmds3hSuS8vifPPiCYZ5zXwy2wBrx6JxkAbkTs7oAx8U6f"]}
arweave         | /upload/ response: 403: Error signature missing v and recoveryParam (argument="signature", value="8d230a13ceb3c6f4ff6c2ad86af1c0b3958fc1fe98a2b260ce828fc204ec32b6", code=INVALID_ARGUMENT, version=bytes/5.7.0)
dbs_1           | Unauthorized: /upload
dbs_1           | [06/Feb/2023 16:32:53] "POST /upload?nonce=1768214571&quoteId=9ee450d4653519a44a178e77a050d1cd&signature=8d230a13ceb3c6f4ff6c2ad86af1c0b3958fc1fe98a2b260ce828fc204ec32b6 HTTP/1.1" 401 30
```

**To Reproduce**
1. Launch the DBS using the Docker-compose.yml file
2. Try to upload some files to DBS_Arweave
3. See the logs.

**Comment by balessan** [comment]
I can see that the Ethers Utilities library is used to check the signature:
```js
	const message = ethers.utils.sha256(ethers.utils.toUtf8Bytes(quoteId + nonce.toString()));
```

whereas on the DBS side we are using a [home-made hash verification](https://github.com/oceanprotocol/decentralized_storage_backend/blob/main/server/oceandbs/utils.py#L20): 

```py
  sha256_hash = hashlib.sha256((str(quote.quoteId) + str(params['nonce'][0])).encode('utf-8')).hexdigest()
```

So both may not be equivalent.

**Comment by MantisClone** [comment]
Hello, @balessan I agree that there's a signature mismatch based on the error message but I am not convinced the message hash is the root cause. 

Are you certain that you sign the hashed message?

Example: https://github.com/oceanprotocol/dbs_arweave/blob/main/test/test.js#L106-L107
```javascript
const message = ethers.utils.sha256(ethers.utils.toUtf8Bytes(quote.quoteId + nonce.toString()));
const signature = await userWallet.signMessage(message);
```

I'm suspicious because the DBS [home-made hash verification](https://github.com/oceanprotocol/decentralized_storage_backend/blob/main/server/oceandbs/utils.py#L20) seems to confuse hashed messages with signatures.

**Comment by balessan** [comment]
Thanks @MantisClone ! I am actually certain that I do not sign the hashed message, so there is the confusion.
I am just missing this step. 

Is my understanding right that signing the message equals to emit a transaction ?

Just need a few additional diggings into the python version of the web3 library, thanks for the pointer which should be enough. If you have any recommendations about a python web3 library which is easy to use, let me know. Otherwise, search engines will do their tricks.

**Comment by MantisClone** [comment]
> Is my understanding right that signing the message equals to emit a transaction ?

Not necessarily.  A transaction must be signed, but not every signed message is a transaction.

# Recommendation

I think you should use [eth-account](https://github.com/ethereum/eth-account) to sign the message. Specifically, I think you should use [`encode_defunct()`](https://eth-account.readthedocs.io/en/stable/eth_account.html#eth_account.messages.encode_defunct) and [`sign_message()`](https://eth-account.readthedocs.io/en/stable/eth_account.html#eth_account.account.Account.sign_message) like so:

```python
>>> from eth_account.messages import encode_defunct
>>> from eth_account.account import Account
>>> message = "hello world"
>>> message_hash = encode_defunct(text=message)
>>> signed_message = Account.sign_message(message_hash, private_key)
>>> signature = signed_message.signature
```

This will yield a `HexStr` that is compatible with the `RawSignature` expected by [`ethers.utils.verifyMessage()`](https://docs.ethers.org/v5/api/utils/signing-key/#utils-verifyMessage)

# Alternatives

You could use Web3.py which also exposes the eth-account interface, but also includes stuff for interacting with smart contracts that you probably don't need.

**Comment by balessan** [comment]
This one is actually closed.
